apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-hello
  namespace: rakesh-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-hello
  template:
    metadata:
      labels:
        app: springboot-hello
    spec:
      containers:
      - name: springboot-hello
        image: rakesh171977/springboot-app  # 👈 matches your Docker push
        ports:
        - containerPort: 8080
