apiVersion: v1
kind: Service
metadata:
  name: springboot-hello-service
  namespace: rakesh-namespace
spec:
  type: NodePort
  selector:
    app: springboot-hello
  ports:
  - port: 8080
    targetPort: 8080
